### ISSUE TITLE
Adding Image Pop-up not showing

### ISSUE THREAD

**Issue by Dark-Wolf-730** [owlchester/kanka-docs#12]
When I try to add an image to a dashboard campaign header the pop-up to add the image is behind the pop-up for editing the Campaign Header. Video attached of my experience. Please fix.
[Screen recording 2023-06-19 12.30.00 PM.webm](https://github.com/owlchester/kanka-docs/assets/110348538/d4932498-4feb-4a0f-a0e2-d5c66a92080c)

**Comment by ilestis** [comment]
Please report errors in the [Discord](https://kanka.io/go/discord) thanks
